### ISSUE TITLE
Project health

### ISSUE THREAD

**Issue by hypnoce** [swaldman/c3p0#155]
Hi,

for more than a year, PR, issues have been accumulated, without any response from repo owners.
Is there a plan to tackle them at some point, or should the community start thinking about a maintained fork ?

Thanks

**Comment by lanmaster** [comment]
Interested too

**Comment by swaldman** [comment]
c3p0 0.10.0 is now a release, including pluggable threading, loom support, much simplified connection testing by default (with simpler configuration for Connection.isValid(...) timeouts), and many many enhancements and improvements, most of which derive from issues that have collected here. 

there's also a more modern, more automated build, which I hope will render it more appealing for me to maintain c3p0 incrementally, rather than put it off into big, occasional (or worse than occasional) batches.

this one was a fair amount of work. I hope it remains useful to some of you.
