### ISSUE TITLE
Is project officially dead?

### ISSUE THREAD

**Issue by hazendaz** [swaldman/c3p0#168]
I work over on https://github.com/psi-probe/psi-probe and I'm considering dropping support for a number of reasons.  While my tool doesn't use directly, users do.  But here are my current reasons.

- No commits in 4 years means project was abandoned.
- The manifest is incorrect with mchange and that should not even be in there for maven users, its causing issues when recompiling jsps.
- There are far better and more supported pooling libraries that have commits far more recent than this.

Seeing little to no traffic here.  If I hear nothing in a couple weeks I have my answer and will drop.  The biggest problem mature or not is the issue with zero commits.  That means its not maintained and java moves fast, 4 years is a lifetime.

**Comment by AccountGc** [comment]
very good

**Comment by FDBenevides** [comment]
Hi @hazendaz. Since I have the same fear about c3p0 could you share some alternative suggestions? Did you test different libs? 
Thanks in advance. Regards

**Comment by hazendaz** [comment]
@hazendaz See https://github.com/brettwooldridge/HikariCP.  Although c3p0 is back to life again.  My usage is just to allow users to use whatever (not direct usage) but if I had to pick that is where I'd go for usage given most my usage at my job is spring boot based and that is first class over there.

**Comment by swaldman** [comment]
As @hazendaz, I guess c3p0 is now undead. c3p0 0.10.0 includes pluggable threading, loom support, much simplified connection testing by default (with simpler configuration for Connection.isValid(...) timeouts), and many many enhancements and improvements, most of which derive from issues that have collected here. there's also a more modern, more automated build, which I hope will render it more appealing for me to maintain c3p0 incrementally, rather than put it off into big, occasional (or worse than occasional) batches. This one was a fair amount of work. I hope it remains useful to some of you.
