### ISSUE TITLE
release latest 0.9.5 to maven central

### ISSUE THREAD

**Issue by lkwg82ATis24** [swaldman/c3p0#49]
Hi,

would you be so kind to release latest version to maven central? Currently there is only the version 0.9.5pre10 available.

Cheers Lars

**Comment by kibertoad** [comment]
Huh?..
http://mvnrepository.com/artifact/com.mchange/c3p0/0.9.5

**Comment by joensson** [comment]
Maven Central is not the same as MvnRepository.

c3p0 0.9.5 is available on both repositories - but I understand the confusion that Lars had.

If you do a search for c3p0 on search.maven.org: http://search.maven.org/#search%7Cga%7C1%7Cc3p0

You get a table that indicates that for groupId "com.mchange", artifactId: "c3p0" the latest version is 0.9.5-pre10. Which is weird because next to the latest version is a link to "all (20)" - which shows the 0.9.5 version just fine. 
I guess it is just the code used for determining which version is greatest at Maven Central that decides that 0.9.5-pre10 is greater than 0.9.5.

**Comment by lkwg82ATis24** [comment]
I admit I only watched the summary page sry, I did not take into account, that another versioning scheme hides the latest one.

According to http://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN401
better would be to follow the official scheme.

So next release candidate could be a 0.9.6-beta1.

**Comment by swaldman** [comment]
Thanks for calling attention to the issue, and for the link.

If I'm understanding that document correctly, qualifiers are only supported after a single decimal place, so I could do 0.9-pre1 or 0.9-beta1, but 0.9.6-xxx just gets treated as a String (and ordered as bigger than 0.9.6 unqualified).

I'll have to think about that... Anyway, thanks. I'd never considered these issues at all.
