### ISSUE TITLE
C3P0Registry.extensionsForToken in ConnectionCustomizer leads to deadlock in unit tests

### ISSUE THREAD

**Issue by skarzhevskyy** [swaldman/c3p0#54]
We are running Persistence UnitTests on build server for every commit.
Recently we added ConnectionCustomizer to our application.  Now some times the unit tests are getting to deadlock.   (The jstack attached http://pyx4j.com/bug/c3p0-54/jstack-deadlock.log)

This is not related to particular test. When I try to reproduce this on local computer I need approximately 1000 build runs with test to get to deadlock.

We have 500 tests with the same connection flow.  Probability of deadlock 1/500,000

Please advise  how we should continue. I can create a standalone unit test or code fragment to reproduce the problem. if required.

Here is my flow.
Tests are not running in parallel. Each test is closing connection Pool.
OS: Windows or Linux;  Latest Java 8, Latest C3P0 0.9.5

There is a ConnectionCustomizer that need information about our ConnectionPoolType.

So we used:

```java
        ComboPooledDataSource dataSource = new ComboPooledDataSource(false);

        Map<String, Object> extensions = new HashMap<>();
        extensions.put(MyConnectionPoolType.class.getName(), myConnectionType);
        dataSource.setExtensions(extensions);

       dataSource.setConnectionCustomizerClassName(MyC3P0ConnectionCustomizer.class.getName());
```

And code fragment form ConnectionCustomizer:

```java
MyC3P0ConnectionCustomizer  extends AbstractConnectionCustomizer  {

    public void onAcquire(Connection c, String dataSourceIdentityToken) throws Exception {

        Map<String, Object> tokenExtensions = extensionsForToken(dataSourceIdentityToken); // <-  deadlock inside this call.
        // other code here
     }
}

```

**Comment by swaldman** [comment]
Thanks for the detailed bug report.

So, the nested locking in C3P0Registry was entirely unnecessary. Removing the nesting should eliminate that deadlock. That's done now, with the fix available in what would be 0.9.6-pre1-SNAPSHOT. It's a trivial, nondisruptive change. If it would be helpful to have that in a 0.9.5.1 release version, let me know.

By the way, why do you set `autoregister` to false?

    ComboPooledDataSource dataSource = new ComboPooledDataSource(false);

I'm a bit surprised you find the extensions, actually, since you ask the datasource not to register itself, and the ConnectionCustomizer relies upon a registered DataSource. In general, the constructor you are using is intended for internal use, to avoid registering temporarily constructed DataSources that result from dereferencing but are ultimately discarded in favor of an already existing DataSource with the same identity. It might have been nonpublic, but the organization of my libraries made that inconvenient. 

How did you come to use that constructor? Are you explicitly `reregistering` the datasource with C3P0Registry (otherwise I'm not sure how your extension lookup ever succeeds).

Thanks again for the very clear, detailed bug report.

**Comment by kibertoad** [comment]
Including this change in 0.9.5.1 would be most appreciated :)

**Comment by skarzhevskyy** [comment]
Steve,  Thanks for fixing.

My C3P0 usage pattern where dictated by requirements to have descriptive JMX names and Many applications working on the same JVM in one tomcat.
   one app JMX looks like this http://pyx4j.com/bug/c3p0-54/jmx-beans.png

  I do call  dataSource.setDataSourceName(appName+poolName)  and only than register it so the name will be readable.
  my code here:  http://pyx4j.com/bug/c3p0-54/ConnectionPoolC3P0.java

  My problem where mainly revolved here http://sourceforge.net/p/c3p0/bugs/121/
  But I was overloaded to grasp your concepts of creating properties 

now I use only this in configuration file
...
com.mchange.v2.c3p0.management.ManagementCoordinator=com.mchange.v2.c3p0.management.ActiveManagementCoordinator
com.mchange.v2.c3p0.management.ExcludeIdentityToken=true
...

  I did not changed my usage pattern, I call java (API) function instead of hard-coded (or consts) string properties. So next time if configuration properties will somehow changes my application will not compile with next library version . This apply to libraries not only to c3p0.

  Look here  how try to configure quartz  http://pyx4j.com/bug/c3p0-54/SchedulerHelper.java
this drives me crazy.  If I would spend more time I would probably found a way to configure it all java way.

**Comment by swaldman** [comment]
I'm glad to see that you've found some of the obscure parts of c3p0's API useful! Sometimes I wonder whether anybody uses this stuff. 

You do call C3P0Registry.reregister(...), so everything should work fine. I also like compiler checked configuration.

There's now a c3p0-0.9.5.1-SNAPSHOT release which contains the fix for the deadlock you reported and a couple of new configuration options. If you get a chance, I'd appreciate any stress you can put it under before I call c3p0-0.9.5.1 a releases.

Thanks again for finding the deadlock!

**Comment by skarzhevskyy** [comment]
Done 
Used, 0.9.5.1-SNAPSHOT from oss.sonatype.org (c3p0-0.9.5.1-20150531.210052-2). Run overnight 2122 tests runs. The problem did not appeared.

**Comment by swaldman** [comment]
Thank you very much for the fast feedback!

**Comment by swaldman** [comment]
OK. 0.9.5.1 is a release, including this fix. Sorry for the delay, thanks again for the help!
