### ISSUE TITLE
Connection test for version 0.9.5.2?

### ISSUE THREAD

**Issue by ihaolin** [swaldman/c3p0#64]
Hello，I see the documentation of [here](http://www.mchange.com/projects/c3p0/)，about the phase:
>
When configuring Connection testing, first try to minimize the cost of each test. If you are using a JDBC driver that you are certain supports the new(ish) jdbc4 API — and if you are using c3p0-0.9.5 or higher! — let your driver handle this for you. jdbc4 Connections include a method called isValid() that should be implemented as a fast, reliable Connection test. By default, c3p0 will use that method if it is present.

So，I use c3p0 0.9.5.2:

````
<dependency>
     <groupId>com.mchange</groupId>
     <artifactId>c3p0</artifactId>
     <version>0.9.5.2</version>
</dependency>
```
then, I write the java code:
```
pool = new ComboPooledDataSource();
pool.setDriverClass("com.mysql.jdbc.Driver" );
pool.setJdbcUrl("jdbc:mysql://localhost:3306/user_db");
pool.setUser("root");
pool.setPassword("");
```
When the connection `wait_timeout`(so，MySQL closed the connection)，and the client still throw a connection failed exception，as if the method `isValid()` doesn't check the connection. is it right?

Can someone help me?

Thanks & Regards.

**Comment by swaldman** [comment]
hi,

you still need to turn on Connection testing, with some mix of testConnectionOnCheckout, testConnectionOnCheckin, and idleConnectionTestPeriod. [just calling pool.setTestConnectionOnCheckout(true) will probably do what you expected to happen automatically.] with newer drivers, there is no need to set preferredTestQuery, because Connection.isValid() can be used.

       smiles,
             Steve

~oo~
Steve Waldman
swaldman@mchange.com

**Comment by ihaolin** [comment]
Ok，I get it. Thanks.
