### ISSUE TITLE
Acquiring connection from c3p0 connection pool

### ISSUE THREAD

**Issue by bhuvangu** [swaldman/c3p0#70]
Can c3p0 provide an api where, when a application request for a connection from the pool, the application can say that it is going to run only readonly queries.
Now if application again request for a connection and is saying that it is only going to run readonly queries then c3p0 is intelligent enough to return already acquired connection instead of blocking another connection from the pool.

Given both request for connection is readonly mode using same jdbc connection for both request is no harm and this will give performance inprovement to applications.

Is this possible? if not , why not?

Ref: How i reached to above idea is during investigation of hibernate and how hibernate uses cp03 (http://stackoverflow.com/questions/36920695/hibernate-and-transaction-using-method-annotation)

**Comment by swaldman** [comment]
hi,

i'm not so sure that this is a workable idea. read-only use or not, Connection objects are frequently not safe for multithreaded access.

(in the JDBC 1.0 spec, Connections were supposed to be thread-safe, only derived Statements and ResultSets were single-thread restricted. but later specs are silent on the point, and the practice both of JDBC implementers and developers has been to presume single-threaded use. c3p0 learned this lesson the hard-way, its statement cache presumed the JDBC 1.0 standard was upheld and sometimes called `close()` on Connections in current use. believing the spec was a mistake that led to years of headaches and deadlocks for drivers that did not live up to the JDBC 1.0 standard. recent versions of c3p0 offer a setting that neurotically prevents concurrent access by the statement cache.)

besides that, i think the suggestion is not so helpful because it presumes acquiring a Connection from the pool is expensive when the whole point of a Connection pool is that they make Connection acquisitions cheap for the application. there is no problem with applications checking out and checking in Connections as needed, on a just-in-time basis. your suggestion tries to solve the problem that Connection pools themselves already exist to solve.

i appreciate the suggestion, and don't mean to be discouraging. but i don't think this idea can work.

**Comment by bhuvangu** [comment]
And readme say 

> although keep in mind he is an abysmal correspondent

hahahah..
Anyway
Thanks for the feedback.
 But is theory does it look like the above will give performance improvement?

Do you think its worth giving a shot where i can hack c3p0 code to emulate the above scenario with atleast postgres jdbc driver and present the results. 
As postgres driver does say that they are thread safe https://jdbc.postgresql.org/documentation/91/thread.html

**Comment by bhuvangu** [comment]
So i hacked the [hibernate](https://github.com/hibernate/hibernate-orm/tree/4.3.8.Final) code. what i  essentially did was that i added the parameter isReadOnly in hibernate `beginTransaction` method and 
added one new methods in `c3p0Provider ` [original code](https://github.com/hibernate/hibernate-orm/blob/4.3.8.Final/hibernate-c3p0/src/main/java/org/hibernate/c3p0/internal/C3P0ConnectionProvider.java)  `getConnection(isReadOnly)` and changed `closeConnection(con)` like below

```
 Map<Connection, Integer> readOnlyConnection = new HashMap<Connection,Integer>();
	@Override
	@SuppressWarnings("UnnecessaryUnboxing")
	public Connection getConnection(boolean willBeUseForReadOnly) throws SQLException {
		System.out.println("Bingo dam" + willBeUseForReadOnly);		
		Connection connection;
                if(!willBeUseForReadOnly) { // not a read only
			return getConnection();
		}
		if(readOnlyConnection.isEmpty()) {
			System.out.println("readOnlyConnection readonly empty");
			connection= getConnection();
			readOnlyConnection.put(connection,1);			
		} else {
			connection = readOnlyConnection.keySet().iterator().next();
			Integer i = readOnlyConnection.get(connection);
			readOnlyConnection.put(connection, i+1);			
			System.out.println("returning "+connection +":::" +(i+1));
		}
		return connection;
	}

	@Override
	public void closeConnection(Connection conn) throws SQLException {
		Integer integer = readOnlyConnection.get(conn);
		if(integer == null || integer == 1){
			readOnlyConnection.remove(conn);
			conn.close();
		}
	}

```
Now with one connection in connection pool i can tell hibernate that this is going to be a readonly transaction and hence can multiplex different readOnly transaction to same connection.

_Why i am trying to multiplex different readOnly Transaction to same connection?_
Consider this very generic pattern
In Hibernate and Annotation and managed objects world, what i have seen a common pattern like
```
@Transactional
public void createStuff(..){
// get entity manager and call persist and other operatation
}
@Transactional
public SomeDtoObject getStuff(..){
// get entity manager and call find and getter to polulate a object to return
}
```
In managed beans the Hibernate transaction is started and commited when we call this methods.

Now lets look at what all happen in such patterns with method which only run readonly queries and what is the connection state during the process.
[1] As soon as we enter the method let say we try to acquire a connection from connection pool. (Connection marked as in use)
[2] my application logic runs and calls hibernate passed the HQL (connection is marked as in use, but not using)
[3] Hibernate parse HQL convert to db query (connection is marked as in use, but not using)
[4] Hibernate run the db query (connection is locked , and in use)
[5] Query run on db and result is send back ((connection is locked , and in use)
[6] Hibernate get the result and convert them to objects (connection is marked as in use, but not using)
[7] My application logic run to do generate DTOs(connection is marked as in use, but not using)
[8] we exist the method (connection is returned to the pool)

Now let say from point [1] to [3] take 50 ms, point[4] take 20 ms and point [6] to [7] take 50 ms,
then we have marked connection as in use for 120 ms and out of which connection was idle for 100 ms. 

Now If i have 8 core db machine and as internet say we keep connection pool of 8.
And 50 request come in for that method then without multiplexing it will take 840 ms, where as with multiplexing it will take 240 ms. Please ref the image (sorry for bad paint job.)

![hibernate_tx_multiplex](https://cloud.githubusercontent.com/assets/1015086/14949777/43252e0c-106a-11e6-801c-2413c55cddf3.png)

**Comment by swaldman** [comment]
So your issue, really, is that your application ends up checking out Connections too early and checking them in too late, preventing use by other clients while it does stuff like running application logic before/after database work, parsing HQL, etc. There's no question that will reduce the rate at which you can serve clients for a fixed pool size. Ideally, you check out a Connection immediately prior to your database work, and check it back in promptly.

If you can't do that, then you could improve your rate of service by having your clients share a single Connection for read only work, sure. But...

- As we've already talked about, in general JDBC Connections aren't thread-safe. Your JDBC driver may offer Thread safe Connections, so OK, but be careful.
- Your issue comes with sections that are marked `@Transactional`. You had better think carefully about what clients will or will not see during their read-only operations on the shared Connection. Suppose that a client updates a table, and then performs a query that should reflect the update. The update goes over a normal, checked-out Connection, but the query is read-only and goes to your multiplexed Connection. Then the client may or may not see the update in her query to the read-only Connection, depending upon the transactional state of the Connection, transaction isolation levels, etc. Is hibernate calling `setAutoCommit(false)`, `commit()`, and `rollback()` on the "read only" Connections? If so having multiple clients and threads at it may be pretty iffy even if your JDBC driver can deal with the concurrency.

I'm not saying that this idea can't work! It might! But it seems like something you'd have to be really careful with. Ideally, your application and hibernate would be designed to better minimize the Connection-checked-out-but-idle period of your code. But if you can't do anything about that, my first suggestion would be to just expand the pool. Sure, that'd mean more open Connections, but the idle periods that provoke the problem suggest that database-load per Connection is lower than it might be. The longer Connections are checked-out-but-idle, the more Connections your application can have checked out at constant load on your DBMS. Of course there are other costs to extra Connections -- open socket Connections, a memory footprint, etc. But those costs might be mild relative to managing the complexity of a clever but potentially dangerous multiplexing arrangement.

**Comment by bhuvangu** [comment]
> The longer Connections are checked-out-but-idle, the more Connections your application can have checked out at constant load on your DBMS
Movement of Enlightenment.

Also just to add:
the point where you mentioned about `what clients will or will not see`... there the plan is to have parameter in `@transaction` , if a method is marked as `@transaction(readonly=true)` then the queries from this will be multiplex and developer will make sure he is not runing any data manipulation query/HQL.
And if `@transaction(readonly=false)`  then we will lock that particular connection till the method ends.

But as you mentioned, i will go with `Movement of enlightenment strategy`.

Next, i need to figure out a way to collect the info of for how much percentage the connection remain idle after checking-out a connection from the c3p0 connection pool during a certain period of time(peak hour).

Any strategy that you can suggested to figure this out ? (Thanks)
